# Plano KPI Mirror 01/09 - PASSO 1: commits (V1 + V3.3 + docs pendentes de 31/08)
# Correr: & "C:\Users\ue_e-snetto\Documents\projetosPython\WATCHERDB_V3.3\docs\context\MIRR2_PASSO1_commits.ps1"

Set-Location "C:\Users\ue_e-snetto\Documents\projetosPython"

Write-Host ">>> Commit 1: V1 - HIST das filas (collector + migration + canonical SECAO 35 + changelog)" -ForegroundColor Cyan
git add "WATCHERDB INTELLIGENCE V1/scripts/collectors/collect_mirroring_status.py" "WATCHERDB INTELLIGENCE V1/database/MIGRATION_MIRRORING_QUEUE_HIST.sql" "WATCHERDB INTELLIGENCE V1/database/INSTALACAO_COMPLETA_UNIFICADA.sql" "WATCHERDB INTELLIGENCE V1/database/CHANGELOG_JOBS_COLETA.md"
git commit -m 'feat(v1 intel): WDB_MIRRORING_QUEUE_HIST - serie temporal das filas de mirroring' -m 'Fase B do plano KPI Mirror (v1-intel GO-com-condicoes, desenho dele): tabela dedicada fora do BLUE/GREEN, append-only, INSERT best-effort apos o store principal (try/except isolado, mesmo DataFrame pos-transform). Retencao 7d no proprio collector - desvio ACEITE pelo v1-intel a nao tocar na usp_purge_kpi_history viva (licao env-slot 31/08). Canonical SECAO 35 no mesmo lote. Fase C (endpoints/RC4) VETADA: exigia VIEW ANY DEFINITION.' -m 'Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>'

Write-Host ">>> Commit 2: V3.3 - triagem + tendencia + drill enriquecido + docs 31/08-01/09" -ForegroundColor Cyan
git add WATCHERDB_V3.3/docs/FEATURE_MATRIX.md WATCHERDB_V3.3/api/routers/intelligence_kpis.py WATCHERDB_V3.3/api/routers/queries/mirroring_diagnosis.py WATCHERDB_V3.3/templates/watcherdb_portal.html WATCHERDB_V3.3/static/i18n/pt.json WATCHERDB_V3.3/static/i18n/en.json WATCHERDB_V3.3/static/i18n/es.json WATCHERDB_V3.3/docs/changelog/CHANGELOG.md WATCHERDB_V3.3/findings-inbox.md WATCHERDB_V3.3/docs/context/CONTEXT.md WATCHERDB_V3.3/docs/context/SOLUCOES.md WATCHERDB_V3.3/docs/context/PLANO_KPI_MIRROR_MELHORIA_2026-09-01.md WATCHERDB_V3.3/docs/context/SCRIPT_MIRROR_REBUILD_FASE0_2026-08-31.sql WATCHERDB_V3.3/docs/context/MIRR2_PASSO1_commits.ps1 WATCHERDB_V3.3/docs/context/MIRR2_PASSO2_migration.ps1 WATCHERDB_V3.3/docs/context/PROMPT_PROPAGACAO_V6_MIRROR_MELHORIA_2026-09-01.md
git commit -m 'feat(v33): KPI Mirror - triagem RESUME-vs-REBUILD + tendencia da fila + drill-down completo' -m 'Plano 01/09 por consenso (v1-intel GO A/B + VETO C; frontend GO). Triagem fila-vs-dados (runbook do owner, validada ao vivo 101GB vs 6.8GB -> REBUILD) no cartao do modal e no drill live; JOIN normalizado ao DATAFILES (VIEW confirmada viva - check bloqueante). Tendencia + suspenso desde via WDB_MIRRORING_QUEUE_HIST (datas honestas: ha pelo menos / a monitorizar). Drill: volumes do PRINCIPAL (alarme <15% no volume do t-log), Dados vs fila, next step abre com triagem. Inclui docs pendentes de 31/08: FINDs 102/103/104, SOLUCOES (2 episodios), rotulo ocorrencias i18n, runbook MirrorRebuild guardado.' -m 'Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>'
git log -2 --format='%h %s'
